/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package easyTask;

import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {

    public static void main(String[] args) throws SQLException {

//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setId(2);
//        project.setName("Novonometeste");
//        project.setDescription("Descrição teste");
//        projectController.save(project);
//        projectController.update(project);
//
//        List<Project> projects = projectController.getAll();
//
//        projectController.removeByName("Novonometeste");
//
//        System.out.println("TOTAL DE  PROJETOS: " + projects.size());
        TaskController taskController = new TaskController();

        Task task = new Task();

        task.setIdProject(1);
        task.setName("Nome");
        task.setDescription("Descriçao");
        task.setIsCompleted(false);
        task.setNotes("Notasss");
        task.setDeadline(new Date());
     
//          taskController.removeById();

        task.setName("outroname");
        taskController.update(task);

//        taskController.save(task);
//        List<Task> tasks = taskController.getAll(1);
//        System.out.println("total de tarefas: " + tasks.size());;
//        System.out.println(tasks);
    }
}
